using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyTitleAttribute("NClass")]
[assembly: AssemblyDescriptionAttribute("Free UML Class diagram editor")]
[assembly: AssemblyConfigurationAttribute("alpha")]
[assembly: AssemblyProductAttribute("NClass")]
[assembly: AssemblyCopyrightAttribute("Copyright (C) 2006 Balázs Tihanyi")]
[assembly: AssemblyVersionAttribute("1.01.128.0")]
[assembly: AssemblyFileVersionAttribute("1.01.128.0")]
[assembly: AssemblyInformationalVersionAttribute("1.01")]

